using Microsoft.EntityFrameworkCore;
using University.App.Interfaces.Courses;
using University.Core.Entities;
using University.Infra.Data;

namespace University.Infra.Repositories.Courses
{
    public class CourseRepository : ICourseRepository
    {
        private readonly UniversityDbContext _context;

        public CourseRepository(UniversityDbContext context)
        {
            _context = context;
        }

        public async Task<IEnumerable<Course>> GetAllCourses()
        {
            return await _context.Courses
                .Include(c => c.Instructor)
                .Include(c => c.Department)
                .Where(c => !c.IsDeleted) // Filter out soft-deleted courses
                .AsNoTracking()
                .ToListAsync();
        }

        public async Task<(IEnumerable<Course> courses, int totalCount)> GetCoursesWithPaginationAsync(int pageNumber, int pageSize)
        {
            var query = _context.Courses
                .Include(c => c.Instructor)
                .Include(c => c.Department)
                .Where(c => !c.IsDeleted)
                .AsNoTracking()
                .AsQueryable();

            var totalCount = await query.CountAsync();
            var courses = await query
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            return (courses, totalCount);
        }

        public async Task<(IEnumerable<Course> courses, int totalCount)> SearchCoursesAsync(string? searchTerm, int? departmentId, int? instructorId, int pageNumber, int pageSize)
        {
            var query = _context.Courses
                .Include(c => c.Instructor)
                .Include(c => c.Department)
                .Where(c => !c.IsDeleted)
                .AsNoTracking()
                .AsQueryable();

            // Apply search filter
            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                searchTerm = searchTerm.ToLower();
                query = query.Where(c => 
                    c.Name.ToLower().Contains(searchTerm) ||
                    c.CourseCode.ToLower().Contains(searchTerm) ||
                    (c.Department != null && c.Department.Name.ToLower().Contains(searchTerm)) ||
                    (c.Instructor != null && c.Instructor.FullName.ToLower().Contains(searchTerm))
                );
            }

            // Apply department filter
            if (departmentId.HasValue)
            {
                query = query.Where(c => c.DepartmentId == departmentId.Value);
            }

            // Apply instructor filter
            if (instructorId.HasValue)
            {
                query = query.Where(c => c.InstructorId == instructorId.Value);
            }

            var totalCount = await query.CountAsync();
            var courses = await query
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            return (courses, totalCount);
        }

        public async Task<Course?> GetCourseById(int id)
        {
            return await _context.Courses
                .Include(c => c.Instructor)
                .Include(c => c.Department)
                .Include(c => c.Enrollments.Where(e => !e.IsDeleted && e.Status != "Rejected")) // Explicitly filter enrollments
                    .ThenInclude(e => e.Student)
                        .ThenInclude(s => s.User) // Include User to get email
                .Where(c => !c.IsDeleted) // Filter out soft-deleted courses
                .AsNoTracking()
                .FirstOrDefaultAsync(c => c.CourseId == id);
        }

        public async Task<IEnumerable<Course>> GetAllCoursesIncludingDeleted()
        {
            return await _context.Courses
                .IgnoreQueryFilters()
                .Include(c => c.Instructor)
                .Include(c => c.Department)
                .AsNoTracking()
                .ToListAsync();
        }

        public async Task<Course?> AddCourse(Course course)
        {
            // Ensure required fields are set
            course.IsDeleted = false;
            course.DeletedAt = null;
            
            // Set timestamps if not already set
            if (course.CreatedAt == default(DateTime))
                course.CreatedAt = DateTime.UtcNow;
            
            if (course.UpdatedAt == default(DateTime))
                course.UpdatedAt = DateTime.UtcNow;

            // Validate CourseCode is not empty (should be generated by service)
            if (string.IsNullOrWhiteSpace(course.CourseCode))
                throw new InvalidOperationException("CourseCode must be generated before saving course.");

            _context.Courses.Add(course);
            await _context.SaveChangesAsync();

            return course;
        }

        public async Task<Course?> UpdateCourse(Course course)
        {
            var existing = await _context.Courses
                .FirstOrDefaultAsync(c => c.CourseId == course.CourseId && !c.IsDeleted);

            if (existing == null)
                return null;

            // Preserve certain fields
            course.IsDeleted = existing.IsDeleted;
            course.DeletedAt = existing.DeletedAt;
            course.CreatedAt = existing.CreatedAt;
            course.UpdatedAt = DateTime.UtcNow;

            _context.Entry(existing).CurrentValues.SetValues(course);
            await _context.SaveChangesAsync();

            return existing;
        }

        public async Task<bool> DeleteCourse(int id)
        {
            var course = await _context.Courses
                .FirstOrDefaultAsync(c => c.CourseId == id && !c.IsDeleted);

            if (course == null)
                return false;

            course.IsDeleted = true;
            course.DeletedAt = DateTime.UtcNow;
            course.InstructorId = null; // Unassign instructor

            await _context.SaveChangesAsync();
            return true;
        }

        public async Task<bool> RestoreCourse(int id)
        {
            var course = await _context.Courses
                .IgnoreQueryFilters()
                .FirstOrDefaultAsync(c => c.CourseId == id);

            if (course == null)
                return false;

            if (!course.IsDeleted)
                throw new InvalidOperationException("Course is not deleted.");

            course.IsDeleted = false;
            course.DeletedAt = null;
            course.UpdatedAt = DateTime.UtcNow;

            await _context.SaveChangesAsync();
            return true;
        }

        public async Task<bool> UpdateCourseInstructor(int courseId, int? instructorId)
        {
            var course = await _context.Courses
                .IgnoreQueryFilters()
                .FirstOrDefaultAsync(c => c.CourseId == courseId);

            if (course == null)
                return false;

            course.InstructorId = instructorId;
            course.UpdatedAt = DateTime.UtcNow;

            await _context.SaveChangesAsync();
            return true;
        }

        public async Task<bool> PermanentlyDeleteCourse(int id)
        {
            var course = await _context.Courses
                .IgnoreQueryFilters()
                .AsNoTracking() // Don't track to avoid navigation property issues
                .FirstOrDefaultAsync(c => c.CourseId == id);

            if (course == null)
                return false;

            // Cascade delete: Remove all related data first using direct delete operations
            // 1. Delete exam submissions related to this course's exams
            var examIds = await _context.Exams
                .IgnoreQueryFilters()
                .Where(e => e.CourseId == id)
                .Select(e => e.ExamId)
                .ToListAsync();

            if (examIds.Any())
            {
                await _context.ExamSubmissions
                    .IgnoreQueryFilters()
                    .Where(s => s.ExamId.HasValue && examIds.Contains(s.ExamId.Value))
                    .ExecuteDeleteAsync();
            }

            // 2. Delete exam questions
            if (examIds.Any())
            {
                await _context.ExamQuestions
                    .IgnoreQueryFilters()
                    .Where(q => examIds.Contains(q.ExamId))
                    .ExecuteDeleteAsync();
            }

            // 3. Delete exams
            await _context.Exams
                .IgnoreQueryFilters()
                .Where(e => e.CourseId == id)
                .ExecuteDeleteAsync();

            // 4. Delete enrollments
            await _context.Enrollments
                .IgnoreQueryFilters()
                .Where(e => e.CourseId == id)
                .ExecuteDeleteAsync();

            // 5. Delete attendance records
            await _context.Attendances
                .IgnoreQueryFilters()
                .Where(a => a.CourseId == id)
                .ExecuteDeleteAsync();

            // 6. Finally, delete the course itself
            await _context.Courses
                .IgnoreQueryFilters()
                .Where(c => c.CourseId == id)
                .ExecuteDeleteAsync();

            return true;
        }

        /// <summary>
        /// Get count of ALL enrollments for a course (including soft-deleted and all statuses)
        /// Used to determine if course has any enrollment history that should be preserved
        /// </summary>
        public async Task<int> GetActiveEnrollmentCountByCourseId(int courseId)
        {
            return await _context.Enrollments
                .IgnoreQueryFilters() // Include soft-deleted enrollments
                .CountAsync(e => e.CourseId == courseId && 
                               (e.Status == "Enrolled" || e.Status == "Pending"));
        }

        public async Task<IEnumerable<Course>> GetCoursesByInstructorId(int instructorId)
        {
            return await _context.Courses
                .Include(c => c.Department)
                .Include(c => c.Instructor)
                .Where(c => c.InstructorId == instructorId && !c.IsDeleted)
                .AsNoTracking()
                .ToListAsync();
        }

        public async Task<int> GetInstructorActiveCourseCount(int instructorId)
        {
            return await _context.Courses
                .Where(c => c.InstructorId == instructorId && !c.IsDeleted)
                .CountAsync();
        }

        public async Task<int> GetInstructorTotalCreditHours(int instructorId)
        {
            return await _context.Courses
                .Where(c => c.InstructorId == instructorId && !c.IsDeleted)
                .SumAsync(c => (int?)c.Credits) ?? 0;
        }

        public async Task<int> GetStudentCurrentSemesterCredits(int studentId, DateTime semesterStartDate)
        {
            return await _context.Enrollments
                .Where(e => e.StudentId == studentId
                            && e.Status == "Enrolled"
                            && e.EnrollmentDate >= semesterStartDate)
                .SumAsync(e => (int?)e.Course.Credits) ?? 0;
        }

        public async Task<int> GetStudentCurrentYearCredits(int studentId, DateTime yearStartDate)
        {
            return await _context.Enrollments
                .Where(e => e.StudentId == studentId
                            && e.Status == "Enrolled"
                            && e.EnrollmentDate >= yearStartDate)
                .SumAsync(e => (int?)e.Course.Credits) ?? 0;
        }

        public async Task<List<string>> GetStudentCompletedCourseCodes(int studentId)
        {
            return await _context.Enrollments
                .Where(e => e.StudentId == studentId && e.Status == "Completed")
                .Select(e => e.Course.CourseCode)
                .Distinct()
                .ToListAsync();
        }

        public async Task<IEnumerable<Course>> GetAllCoursesByDepartmentId(int departmentId)
        {
            return await _context.Courses
                .Include(c => c.Instructor)
                .Include(c => c.Department)
                .Where(c => c.DepartmentId == departmentId && !c.IsDeleted)
                .AsNoTracking()
                .ToListAsync();
        }

        public async Task<IEnumerable<Course>> GetCoursesByDepartmentForStudent(int departmentId)
        {
            return await GetAllCoursesByDepartmentId(departmentId);
        }

        public async Task<bool> IsCourseBelongsToDepartment(int courseId, int departmentId)
        {
            return await _context.Courses
                .AnyAsync(c => c.CourseId == courseId && c.DepartmentId == departmentId && !c.IsDeleted);
        }
    }
}