using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace University.App.Validators
{
    // Custom validation attributes for Student
    public class ValidStudentCodeAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object? value, ValidationContext validationContext)
        {
            // Allow empty/null values - will be auto-generated by the service
            if (value == null || string.IsNullOrWhiteSpace(value.ToString()))
                return ValidationResult.Success!;

            string code = value.ToString()!;

            // Must start with letter, can contain alphanumeric
            if (!Regex.IsMatch(code, @"^[A-Za-z][A-Za-z0-9]*$"))
                return new ValidationResult("Student code must start with a letter and contain only letters and numbers");

            // Length between 3 and 20 characters
            if (code.Length < 3 || code.Length > 20)
                return new ValidationResult("Student code must be between 3 and 20 characters");

            return ValidationResult.Success!;
        }
    }
    public class ValidNameAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object? value, ValidationContext validationContext)
        {
            if (value == null || string.IsNullOrWhiteSpace(value.ToString()))
                return new ValidationResult("Name is required");

            string name = value.ToString()!;

            // Must contain only letters, spaces, hyphens, and apostrophes
            if (!Regex.IsMatch(name, @"^[A-Za-z\s\-\']+$"))
                return new ValidationResult("Name can only contain letters, spaces, hyphens, and apostrophes");

            // Must not start or end with space
            if (name.Trim() != name)
                return new ValidationResult("Name cannot start or end with spaces");

            // Must have at least 2 characters
            if (name.Length < 2)
                return new ValidationResult("Name must be at least 2 characters long");

            return ValidationResult.Success!;
        }
    }
}
