using System.ComponentModel.DataAnnotations;

namespace University.App.DTOs
{
    /// <summary>
    /// Basic Course DTO - Used for reading course information in API responses
    /// </summary>
    public class CourseDTO
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int CreditHours { get; set; }
        public int InstructorId { get; set; }
        public string InstructorName { get; set; } = string.Empty;
        public string CourseCode { get; set; } = string.Empty;
        public int? DepartmentId { get; set; }
        public string DepartmentName { get; set; } = string.Empty;
        public DateTime? DeletedAt { get; set; }
    }

    /// <summary>
    /// Course Update DTO - Enforces validation rules for updating existing courses
    /// </summary>
    public class UpdateCourseDTO
    {
        /// <summary>
        /// VALIDATION ENHANCED: Course name validation for updates
        /// - Required: Course must always have a meaningful name
        /// - StringLength(80): Prevents excessively long course names
        /// - RegularExpression: Must contain at least one letter (prevents all-numeric names)
        /// - Service-level: Validates new instructor exists (if changed)
        /// - Service-level: Validates instructor workload (if instructor changes)
        /// </summary>
        [Required(ErrorMessage = "Course name is required")]
        [StringLength(80, MinimumLength = 3, ErrorMessage = "Course name must be between 3 and 80 characters")]
        [RegularExpression(@".*[a-zA-Z]+.*", ErrorMessage = "Course name must contain at least one letter")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// VALIDATION ENHANCED: Credit hours validation for updates
        /// - Required: Every course must have assigned credit hours
        /// - Range(1, 6): Standard academic credit range (1-6 credits per course)
        /// - Service-level: Validates total instructor credit hours doesn't exceed 12 (if instructor changes)
        /// </summary>
        [Required(ErrorMessage = "Credit hours are required")]
        [Range(1, 6, ErrorMessage = "Credit hours must be between 1 and 6")]
        public int CreditHours { get; set; }

        /// <summary>
        /// VALIDATION ENHANCED: Instructor assignment validation for updates
        /// - Required: Course must have an assigned instructor
        /// - Service-level: Validates instructor exists in system
        /// - Service-level: Validates instructor doesn't exceed max courses (2 courses)
        /// - Service-level: Validates instructor doesn't exceed max credit hours (12 hours)
        /// - Service-level: Allows same instructor (self-assignment)
        /// </summary>
        [Required(ErrorMessage = "Instructor ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Instructor ID must be a valid positive number")]
        public int InstructorId { get; set; }

        /// <summary>
        /// VALIDATION ENHANCED: Department assignment validation for updates
        /// - Used to maintain course-department relationship
        /// - Service-level: Validates department exists in system
        /// - Purpose: Ensures course stays within correct department context
        /// </summary>
        [Required(ErrorMessage = "Department ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Department ID must be a valid positive number")]
        public int DepartmentId { get; set; }
    }

    /// <summary>
    /// Course Creation DTO - Enforces comprehensive validation rules for new course creation
    /// </summary>
    public class CreateCourseDTO
    {
        /// <summary>
        /// VALIDATION ENHANCED: Course code is auto-generated by the backend
        /// - Not required from client: Backend will auto-generate based on department
        /// - Format: First 3 chars of single-word dept OR first char of each word (multi-word)
        /// - Plus incrementing 2-digit number (e.g., "CS01", "CS02", "MAT01")
        /// - Service-level: Uniqueness check (no duplicate course codes allowed)
        /// - Note: Client should NOT provide this field, backend generates it
        /// </summary>
        public string? CourseCode { get; set; } // Auto-generated, not required from client

        /// <summary>
        /// VALIDATION ENHANCED: Course name validation
        /// - Required: Course must have a meaningful name
        /// - StringLength(80): Prevents excessively long course names
        /// - RegularExpression: Must contain at least one letter (prevents all-numeric names)
        /// - Service-level: Used with course code for comprehensive identification
        /// </summary>
        [Required(ErrorMessage = "Course name is required")]
        [StringLength(80, MinimumLength = 3, ErrorMessage = "Course name must be between 3 and 80 characters")]
        [RegularExpression(@".*[a-zA-Z]+.*", ErrorMessage = "Course name must contain at least one letter")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// VALIDATION ENHANCED: Credit hours validation
        /// - Required: Every course must have assigned credit hours
        /// - Range(1, 6): Standard academic credit range
        /// - Service-level: Validates instructor workload after assignment
        ///   * Max 2 courses per instructor
        ///   * Max 12 total credit hours per instructor
        /// </summary>
        [Required(ErrorMessage = "Credit hours is required")]
        [Range(1, 6, ErrorMessage = "Credit hours must be between 1 and 6")]
        public int CreditHours { get; set; }

        /// <summary>
        /// VALIDATION ENHANCED: Instructor assignment validation
        /// - Required: Every course must have an assigned instructor
        /// - Service-level: Validates instructor exists in system
        /// - Service-level: Validates instructor doesn't exceed:
        ///   * Maximum 2 courses per instructor
        ///   * Maximum 12 credit hours per instructor
        /// - Service-level: Ensures workload rules compliance
        /// </summary>
        [Required(ErrorMessage = "Instructor ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Instructor ID must be a valid positive number")]
        public int InstructorId { get; set; }

        /// <summary>
        /// VALIDATION ENHANCED: Department assignment validation
        /// - Required: Every course must belong to a department
        /// - Service-level: Validates department exists in system
        /// - Service-level: Enforces department restriction (ENFORCE_DEPARTMENT_RESTRICTION = true)
        /// - Purpose: Ensures students can only access courses in their department
        /// </summary>
        [Required(ErrorMessage = "Department ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Department ID must be a valid positive number")]
        public int DepartmentId { get; set; }
    }

    // DTO for showing course info in enrollment list
    public class EnrollCourseDTO
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; } = string.Empty;
        public string CourseCode { get; set; } = string.Empty;
        [Range(1, 6)]
        public int CreditHours { get; set; }
        public string DepartmentName { get; set; } = string.Empty;
    }

    // Creating Enrollment
    /// <summary>
    /// VALIDATION ENHANCED: Comprehensive input validation to prevent invalid enrollments
    /// </summary>
    public class CreateEnrollmentDTO
    {
        /// <summary>
        /// Student identifier validation
        /// - Required: Every enrollment must specify a student
        /// - Range: Must be a valid positive student ID (prevents 0 or negative values)
        /// - Service-level: Validates student exists in database
        /// </summary>
        [Required(ErrorMessage = "Student ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Student ID must be a valid positive number")]
        public int StudentId { get; set; }

        /// <summary>
        /// Course identifier validation
        /// - Required: Every enrollment must specify a course
        /// - Range: Must be a valid positive course ID (prevents 0 or negative values)
        /// - Service-level: Validates course exists and is not deleted
        /// </summary>
        [Required(ErrorMessage = "Course ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Course ID must be a valid positive number")]
        public int CourseId { get; set; }

        /// <summary>
        /// Student name (populated by service, validated for display)
        /// - StringLength: Max 150 chars (standard name field limit)
        /// - Service-level: Trimmed to prevent whitespace pollution
        /// - Display: Used in enrollment records and grade reports
        /// - NOT REQUIRED on input - populated by service
        /// </summary>
        [StringLength(150, ErrorMessage = "Student name cannot exceed 150 characters")]
        public string? StudentName { get; set; }

        /// <summary>
        /// Course name (populated by service, validated for display)
        /// - StringLength: Max 80 chars (matches Course creation constraint)
        /// - Service-level: Trimmed to prevent whitespace pollution
        /// - Display: Used in enrollment records and student transcripts
        /// - NOT REQUIRED on input - populated by service
        /// </summary>
        [StringLength(80, ErrorMessage = "Course name cannot exceed 80 characters")]
        public string? CourseName { get; set; }

        /// <summary>
        /// Credit hours (populated by service from course data)
        /// - Range: 1-6 (standard academic credit range)
        /// - Service-level: Validated against semester/annual limits
        /// - NOT REQUIRED on input - populated by service from Course entity
        /// </summary>
        public int? CreditHours { get; set; }

        /// <summary>
        /// Course code (populated by service)
        /// - StringLength: Max 10 chars (standard course code format)
        /// - Format: e.g., "CS01", "MAT02", "PHYS03"
        /// - NOT REQUIRED on input - populated by service
        /// </summary>
        [StringLength(10, ErrorMessage = "Course code cannot exceed 10 characters")]
        public string? CourseCode { get; set; }
    }

    // Student enrollment view DTO
    /// <summary>
    /// VALIDATION ENHANCED: Comprehensive output validation to ensure data integrity
    /// </summary>
    public class StudentEnrollmentDTO
    {
        /// <summary>
        /// Enrollment identifier
        /// - Display: Unique identifier for enrollment record
        /// </summary>
        [Range(1, int.MaxValue)]
        public int EnrollmentId { get; set; }

        /// <summary>
        /// Student identifier
        /// - Required: Links enrollment to specific student
        /// - Used for attendance marking and grade management
        /// </summary>
        [Range(1, int.MaxValue)]
        public int? StudentId { get; set; }

        /// <summary>
        /// Student code for display
        /// - Display: e.g., "CS20240001"
        /// </summary>
        [StringLength(20, ErrorMessage = "Student code cannot exceed 20 characters")]
        public string StudentCode { get; set; } = string.Empty;

        /// <summary>
        /// Student email for display
        /// - Display: Student's email address
        /// - StringLength: Max 100 chars
        /// </summary>
        [StringLength(100, ErrorMessage = "Student email cannot exceed 100 characters")]
        [EmailAddress(ErrorMessage = "Invalid email format")]
        public string StudentEmail { get; set; } = string.Empty;

        /// <summary>
        /// Student name validation for display
        /// - Required: Enrollment must show who is enrolled
        /// - StringLength: Max 150 chars
        /// - Service-level: Trimmed to prevent whitespace display issues
        /// </summary>
        [Required(ErrorMessage = "Student name is required")]
        [StringLength(150, ErrorMessage = "Student name cannot exceed 150 characters")]
        public string StudentName { get; set; } = string.Empty;

        /// <summary>
        /// Course name validation for display
        /// - Required: Enrollment must show which course
        /// - StringLength: Max 80 chars
        /// - Service-level: Matches course creation constraints
        /// </summary>
        [Required(ErrorMessage = "Course name is required")]
        [StringLength(80, ErrorMessage = "Course name cannot exceed 80 characters")]
        public string CourseName { get; set; } = string.Empty;

        /// <summary>
        /// Course credit hours
        /// - Range: 1-6 (standard academic range)
        /// - Display: Used for academic planning calculations
        /// </summary>
        [Range(1, 6, ErrorMessage = "Credit hours must be between 1 and 6")]
        public int CreditHours { get; set; }

        /// <summary>
        /// Course identifier code
        /// - StringLength: Max 10 chars
        /// - Display: e.g., "CS01", "MAT02"
        /// </summary>
        [StringLength(10, ErrorMessage = "Course code cannot exceed 10 characters")]
        public string CourseCode { get; set; } = string.Empty;

        /// <summary>
        /// Department name validation for display
        /// - Required: Shows course department affiliation
        /// - StringLength: Max 100 chars
        /// - Display: Important for department restriction verification
        /// </summary>
        [Required(ErrorMessage = "Department name is required")]
        [StringLength(100, ErrorMessage = "Department name cannot exceed 100 characters")]
        public string DepartmentName { get; set; } = string.Empty;

        /// <summary>
        /// Instructor name for display
        /// - Optional: Shows who teaches the course
        /// - StringLength: Max 150 chars
        /// - Display: Used in student course listings
        /// </summary>
        [StringLength(150, ErrorMessage = "Instructor name cannot exceed 150 characters")]
        public string? InstructorName { get; set; }

        /// <summary>
        /// Enrollment status field validation
        /// - Required: Must always have a status
        /// - AllowedValues: "Enrolled", "Dropped", "Completed", "Withdrawn"
        /// - Service-level: Enforced via validation and status transition rules
        /// - Default: "Enrolled" (initial status)
        /// </summary>
        [Required(ErrorMessage = "Enrollment status is required")]
        [StringLength(20, ErrorMessage = "Status cannot exceed 20 characters")]
        public string Status { get; set; } = "Enrolled";

        /// <summary>
        /// Final grade (0-100 scale)
        /// - Optional: Null until exams are graded
        /// - Range: 0-100 (percentage scale)
        /// - Display: Shows numeric grade point
        /// - Service-level: Calculated from exam submission scores
        /// </summary>
        [Range(0, 100, ErrorMessage = "Final grade must be between 0 and 100")]
        public decimal? FinalGrade { get; set; }

        /// <summary>
        /// Letter grade representation
        /// - Optional: Null until exams are graded
        /// - AllowedValues: "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F"
        /// - StringLength: 2-3 chars (e.g., "A+" is 2 chars, "A-" is 2 chars)
        /// - Service-level: Calculated from FinalGrade percentage
        /// </summary>
        [StringLength(3, MinimumLength = 1, ErrorMessage = "Grade letter must be between 1 and 3 characters")]
        [RegularExpression(@"^[A-F][+-]?$|^F$", ErrorMessage = "Invalid letter grade format")]
        public string? GradeLetter { get; set; }

        /// <summary>
        /// Enrollment date timestamp
        /// - Display: When student enrolled in course
        /// - Audit: Used for enrollment history and compliance
        /// </summary>
        public DateTime EnrollmentDate { get; set; }

        /// <summary>
        /// Course active status
        /// - Display: Boolean indicating if course is still active
        /// - True: Course not deleted, student can still access
        /// - False: Course deleted, student enrollment is inactive
        /// </summary>
        public bool IsCourseActive { get; set; } = true;
    }
    // Courses taught by Instructor
    public class InstructorCoursesDTO
    {
        public int CourseId { get; set; }
        public int InstructorID { get; set; }
        public string InstructorName { get; set; } = string.Empty;
        public string CourseName { get; set; } = string.Empty;
        public int CreditHours { get; set; }
        public string CourseCode { get; set; } = string.Empty;
        public string DepartmentName { get; set; } = string.Empty;
    }
    public class CourseCompletionStatusDTO
    {
        public int EnrollmentId { get; set; }
        public int StudentId { get; set; }
        public string StudentName { get; set; } = string.Empty;
        public int CourseId { get; set; }
        public string CourseName { get; set; } = string.Empty;
        public string CourseCode { get; set; } = string.Empty;
        public bool IsCompleted { get; set; }
        public int TotalExams { get; set; }
        public int SubmittedExams { get; set; }
        public decimal? AverageScore { get; set; }
        public decimal? FinalGrade { get; set; }
        public string? GradeLetter { get; set; }
        public string Status { get; set; } = string.Empty; // "Completed", "In Progress", "Failed"
        public List<ExamCompletionDTO> ExamDetails { get; set; } = new();
    }

    public class ExamCompletionDTO
    {
        public int ExamId { get; set; }
        public string ExamTitle { get; set; } = string.Empty;
        public decimal Score { get; set; }
        public decimal TotalPoints { get; set; }
        public decimal Percentage { get; set; }
        public bool IsPassed { get; set; }
        public bool IsSubmitted { get; set; }
        public DateTime? SubmittedAt { get; set; }
    }
}